"use server";

import { fal } from "@fal-ai/client";
import { BriaSceneSchema } from "@/types/bria";

// ENDPOINTS
const BRIA_ENDPOINT = "bria/fibo/generate"; // Stage 1: Scene Generator
const ICLIGHT_ENDPOINT = "fal-ai/iclight-v2"; // Stage 2: Relighting/Compositor

export async function submitGenerationJob(
  skuFileBase64: string,
  schema: BriaSceneSchema
) {
  // 0. Safety Check: Mock Mode if no key
  if (!process.env.FAL_KEY) {
    console.log("⚠️ No FAL_KEY found. Simulating Generation.");
    await new Promise((resolve) => setTimeout(resolve, 3000));
    return {
      imageUrl:
        "https://fal.media/files/monkey/A_futuristic_coke_bottle_on_mars.png",
      status: "COMPLETED",
    };
  }

  try {
    // 1. Upload SKU (The Shoe) to Fal Storage
    const skuUrl = await fal.storage.upload(
      new Blob([Buffer.from(skuFileBase64.split(",")[1], "base64")])
    );

    // --- STAGE 1: BRIA FIBO (Generate the Scene) ---
    console.log("Stage 1: Generating Scene with Bria...");

    // Construct a Rich Prompt
    // We explicitly list objects to ensure "Mount Fuji" appears, not just "Sunny Resort"
    const objectsString = schema.structured_prompt.objects
      .map((obj) => `${obj.name} (${obj.location})`)
      .join(", ");

    const briaPrompt = `
      ${schema.structured_prompt.background_setting}. 
      Objects in scene: ${objectsString}. 
      Mood: ${schema.structured_prompt.aesthetics.mood_atmosphere}.
      High quality, photorealistic background plate, negative space in center for product.
    `.trim();

    const briaResult: any = await fal.subscribe(BRIA_ENDPOINT, {
      input: {
        prompt: briaPrompt,
        aspect_ratio: "4:5",
        num_inference_steps: 30,
      },
    });

    // Extract the generated background URL
    const bgImageUrl = briaResult.data.images[0].url;

    // --- STAGE 2: IC-LIGHT V2 (Relight & Merge) ---
    console.log("Stage 2: Relighting Product into Scene...");

    // Map Agent's Lighting Decision to IC-Light's Physical Model
    let lightingPreference = "None";
    const direction = schema.structured_prompt.lighting.direction;
    if (["Left", "Right", "Top", "Bottom"].includes(direction)) {
      lightingPreference = direction;
    }

    const icLightResult = await fal.subscribe(ICLIGHT_ENDPOINT, {
      input: {
        image_url: skuUrl, // The Foreground (Shoe) - Locked Pixels
        background_image_url: bgImageUrl, // The Background - Generated by Bria

        // The prompt here reinforces the lighting style
        prompt: "Product shot, realistic lighting, 8k, high fidelity",
        initial_latent: lightingPreference,
        
        guidance_scale: 5.0,
        num_inference_steps: 28,
        enable_safety_checker: false,
      },
      logs: true,
      onQueueUpdate: (update) => {
        if (update.status === "IN_PROGRESS") {
          console.log("Pipeline Running...");
        }
      },
    });

    // Handle potential response structure variations
    const finalImageUrl = icLightResult.data.images[0].url;

    return {
      imageUrl: finalImageUrl,
      status: "COMPLETED",
    };
  } catch (error) {
    console.error("Fal Pipeline Error:", error);
    throw new Error("Generation Failed");
  }
}